title: austin hartman
author: Austin Hartman
email: hartmana99@gmail.com
description:
#sports, software, computer science, nba, soccer, fifa, data science

# social links
github_username:  austinhartman
rss: rss

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

plugins:
 - jekyll-feed
 - jekyll-seo-tag
